### PR TITLE
[WIP] - Fix for issue #346

### PR DESCRIPTION
**Pull request by Arbalest007**
# Description

The purpose of this fix is to disable the vertical scrolling when the Brush Effect is selected on "Filter Images." I am able to disable the vertical scrolling entirely but vertical edits are still not detected properly by `mPhotoEditor.` 

Specifically, I can disable the scroll completely on the `ScrollView` that is the parent for `mPhotoEditorView`. I'm not entirely familiar with the codebase yet, however, once the `mPhotoEditor` is instantiated it seems that the `PhotoEditorView` does not detect touches anymore as it's handled by the `PhotoEditor` object `mPhotoEditor.` 

In essence, I'm not sure where to proceed from here as PhotoEditor.java is Read-Only, and from the debug Log statements I put in, it seems that I can't set the `requestDisallowInterceptTouchEvent()` properly to ignore scrolling in the parent `ScrollView` since `mPhotoEditorView` is not detecting any touches at all (It seems to be handled by `mPhotoEditor` after it is built on line 303 in ImageEditor.java.
 
---**WORK IN PROGRESS**--- Fix for #346 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Arbalest007** [comment]
@Swati4star I've made a pull request for the code I have so far. However, I've run into some roadblocks with getting access to the parent for the `mPhotoEditor` object to disable the touch event interception from the `ScrollView.` As I've noted in the pull request, I'm not entirely familiar with the codebase yet but do you have any suggestions for where I can go from here?

**Comment by Swati4star** [comment]
Actually, even I was stuck with how to disable scroll on this view.
Disabling the scroll on `scrollview` is not doing the trick.

PhotoEditor is readonly, because we are importing it as a library. Maybe, we should create issue for this  in photoeditor repository : https://github.com/burhanrashid52/PhotoEditor

**Comment by Swati4star** [comment]
Created this issue : https://github.com/burhanrashid52/PhotoEditor/issues/90

**Comment by Swati4star** [comment]
Closing this one, as it is dependent on PhotoEditor for now

**Pull request closed without merging**
