### PR TITLE
Fix #53 - UI Change in CropImageActivity

### LINKED ISSUE #53: Converting to PDF is too slow
Converting to PDF is too slow in Lenovo YT3-X50F and HUAWEIG750-T00. is it the image to big (i see the image is 2M in album ) or others?

you can refer to the websites  :

https://github.com/zetbaitsu/Compressor

https://github.com/zetbaitsu/Compressor

### LINKED ISSUE #653: [Edit Images] Few UI Changes
Few UI changes in Edit Images option of ImagesToPDF Fragment

### Changes to be done
* Increase size of `prev` and `next` buttons
* Remove left and right margin of `Rotate` and `Save Current` button 
* Change text `Crop Image No. i` to `Crop Image i of n`
* Remove Toast `Images Sucessfully Croped` as Snackbar is there with same message.

### PR DESCRIPTION
**Pull request by piedcipher**
* Some UI changes in [CropImageActivity](https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/activity/CropImageActivity.java) & [activity_crop_image_activity](https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/res/layout/activity_crop_image_activity.xml)
    * Increased size of `Previous` & `Next` Buttons.
    * Removed left & right margins of `Rotate` & `Save Current` Buttons.
    * Changed text to `Crop image No. i of n` from `Crop image No. i`.
    * Removed Toast `Images Successfully Cropped`.

**Screenshots**

Fixes #653

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by vyankatesh24** [comment]
@piedcipher 
Remove text `No` from `Crop Image No. i of n`
Remove left and right space around text from buttons, Save Current and Rotate also keep some space in between them.

**Comment by piedcipher** [comment]
> Remove left and right space around text from buttons, Save Current and Rotate

I don't understand this

**Comment by piedcipher** [comment]
Gotcha! Sending PR

**Comment by piedcipher** [comment]
**New Screenshot**

**Comment by vyankatesh24** [comment]
* Change `Save Current` to `Save` so that `Crop Image...` will come in single line.
* Make `i` capital in `Crop image...`

**Comment by piedcipher** [comment]
**New Screenshot** (Pushed New Changes)

**Comment by vyankatesh24** [comment]
@piedcipher 
Just the last change, increase the width little bit of `Save Button` it seems too small.

**Comment by piedcipher** [comment]
**Made Suggested Changes**
- Increased width of Save button
- Aligned `Next`, `Crop Image i of n` & `Previous` in a line.

**Screenshot**

**Comment by vyankatesh24** [comment]
Great Job @piedcipher

**Pull request merged**
