### PR TITLE
zip to pdf in fav

### LINKED ISSUE #734: Add ZipToPdf in Favourite
No option to add zip to pdf in favourite

### Steps to reproduce
* Open App
* Click Favourite Menu in ActionBar
* Click FAB
* There isn't ZipToPDF option in an opened screen.

### Expected behaviour
There should be a option to add it.

### Would you like to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description
Added ZipToPdf in favourite section
Screenshot_20190425-142125

Fixes #734 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ni3verma** [comment]
@Swati4star @vyankatesh24 
*I need help with this*
I have added ZipToPdf preference, but on clicking it, I don't know why it doesn't show up in favourites screen.
I have written similar code as in #696

**Comment by Ni3verma** [comment]
@rob729 , please have a look. You have done similar thing in your PR #696

**Comment by rob729** [comment]
@Ni3verma I looked at your code and I found no mistake.
Can you attach a gif in which you add zip_to_pdf and excel_to_pdf in your favorites?

**Comment by Ni3verma** [comment]
It only show excel to pdf.

**Comment by vyankatesh24** [comment]
> @Swati4star @vyankatesh24
> _I need help with this_
> I have added ZipToPdf preference, but on clicking it, I don't know why it doesn't show up in favourites screen.
> I have written similar code as in #696

Let me check

**Comment by sidhuparas** [comment]
In `Constants`, change the following:
`    public static final String ZIP_TO_PDF_KEY = "ZIP to PDF";`

Note that I changed `Zip` to `ZIP`.

**Comment by Ni3verma** [comment]
@sidhuparas how will it solve the problem? 🤔

**Comment by sidhuparas** [comment]
@Ni3verma I didn't get the time to review whole Favourites logic but I saw to Keys in the code with one being capital and other normal case. The change worked for me.

**Comment by Ni3verma** [comment]
please review and merge now.

**Pull request merged**
