### PR TITLE
Update MainActivity.java

### PR DESCRIPTION
**Pull request by tejasvisoi**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by tejasvisoi** [comment]
Reducing the line of code error in that specific block

**Comment by Swati4star** [comment]
But that shouldn't break the build.

**Comment by tejasvisoi** [comment]
I guess some error might have occured though I made it sure that nothing in the code changes.

**Comment by Swati4star** [comment]
@tejasvisoi Are you looking into this?

**Comment by Swati4star** [comment]
Closing due to inactivity. Feel free to reopen if you work on it further.

**Pull request closed without merging**
