### PR TITLE
Updated Welcome Activity

### LINKED ISSUE #692: Update screenshots in Welcome Activity
### What to do?
* Add Fragment for `Excel to PDF` Feature.
* Update screenshots on the available fragments (most of them are older)
* Use same device image, for all screenshot to embed into (It is different for some now).

### PR DESCRIPTION
**Pull request by jddeep**
# Description
Updated Welcome Activity.
create_pdf
excel_pdf
merge_pdf
view_pdf

Fixes #692 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 Please review and merge.

**Comment by vyankatesh24** [comment]
@jddeep 
Error while swiping fragments.

```
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at swati4star.createpdf.activity.WelcomeActivity$MyViewPagerAdapter.instantiateItem(WelcomeActivity.java:127)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1224)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
        at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:2005)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2135)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3194)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
        at android.view.View.dispatchPointerEvent(View.java:10261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4503)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4368)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4054)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4111)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6346)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6320)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6281)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6452)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
```

**Comment by jddeep** [comment]
@vyankatesh24 What should be the resolution of the images?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 What should be the resolution of the images?

As per earlier images `home.png`.
Around 600*900

**Comment by jddeep** [comment]
@vyankatesh24 Made the changes. Please review.

**Pull request merged**
