### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by soham4abc**
# Description

just noticed and improved the readme

# Checklist:
- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my own code
- [not needed ] I have commented my code, particularly in hard-to-understand areas
- [ yes] I have made corresponding changes to the documentation
- [yes ] My changes generate no new warnings

### CODE REVIEW

**Review by codegsaini — APPROVED** [review]
Great work ! Keep fixing ...

## SideNote~
In your check list,
- Instead of '[yes ]' you should write '[x]'
- If you needed it in future instead of '[no ]' you should leave the braces empty '[]'
- Instead of '[not needed ]' you should remove the line/task

**Comment by soham4abc** [comment]
Ok thanks.... I am new to this codebase... And exploring still... Thank you for guiding me to this codebase's guidelines!

**Comment by soham4abc** [comment]
Will anyone else merge? Or should I ?

**Comment by Swati4star** [comment]
Thanks @soham4abc. I'll be merging this CL. Glad to see your first contribution to this repo 👍 


Thanks @codegsaini for taking a look at this CL :)

**Comment by codegsaini** [comment]
> Ok thanks.... I am new to this codebase... And exploring still... Thank you for guiding me to this codebase's guidelines!

@soham4abc Your welcome, I'm glad that you learnt something new! Don't hesitate ever to get my support. :)



> Will anyone else merge? Or should I ?

Only owner of repository can merge pull requests!

**Comment by codegsaini** [comment]
@Swati4star Welcome :)

**Pull request merged**
