### PR TITLE
Fixed image persisting between image select activities.

### PR DESCRIPTION
**Pull request by blottn**
Fixed issue #24 , allowing for image selections to persist when you leave the image selection screen and return.

### CODE REVIEW

**Comment by Swati4star** [comment]
Squash these commits into a single one.
Great Work! 👍

**Comment by Swati4star** [comment]
[Squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

**Comment by blottn** [comment]
May require further squashing. Give me a moment to fiddle with some git stuff.

**Comment by blottn** [comment]
Should be squashed now!

**Comment by Swati4star** [comment]
Merged. Thanks 👍

**Pull request closed without merging**
