### PR TITLE
Add themes to the app

### LINKED ISSUE #145: Add themes to the app that can be chosen by the user
Add themes to the app that can be chosen by the user like:

1) Black (Also known as AMOLED theme)
2) Dark
3) White (Already exists)
4) Any other variation(s) that you think would look good

### PR DESCRIPTION
**Pull request by sasfmlzr**
# Description

I'm add black, dark and white themes in settings. A lot has been done, so if you find bugs, write. All the bugs I found are fixed. I'm delete all hardcoded colours in layouts.

White theme:
image

Black theme:
image

Dark theme:
image

Settings:
image

If you want create new Activity with toolbar, create toolbar. :) 

Fixes #145 Add themes to the app that can be chosen by the user.

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
I checked it out locally, I found these bugs:

1. In black & dark theme, the bottom bar (`View Files`) at the bottom is not quiet visible. (In light theme, it's color is orange, so its quite easily visible)

screenshot 2018-09-27 at 9 34 34 pm


2. In black & dark theme, the bottom sheet overlaps on the content
screenshot 2018-09-27 at 9 35 33 pm

**Comment by Swati4star** [comment]
Can you change the icon color to white in black & dark theme.
screenshot 2018-09-27 at 9 37 00 pm

**Comment by sasfmlzr** [comment]
You have added a number of new png files. Do we need those? Can't we work with drawables only?
I downloaded icon from Material.io. I always did. If necessary I can delete unnecessary.

**Comment by Swati4star** [comment]
haha! No need of adding them in the translated language. English is fine.

I meant, instead of pngs, we can use vector drawable files

**Comment by sasfmlzr** [comment]
image
Fixed.

**Comment by Swati4star** [comment]
- The bottom sheet is not that much visible in black theme
- history icons are not visible in black theme
- You have removed the horizontal divider below the `Create PDF` button. There used be a orange horizontal line. This has been removed in text to PDF fragment too.
screenshot 2018-09-27 at 11 46 55 pm
- The text `Select Images`, `Create PDF` is supposed to be all caps.
- A lot of color discrepancies are there. See below. Few icons are grey, few are white. Also, at bottom strip, the text should be white
screenshot 2018-09-27 at 11 48 39 pm

**Comment by sasfmlzr** [comment]
Fixed.
I'm add custom attribute iconTintOnCard for swati4star.createpdf.customviews.MyCardView.
image
 
image

image

**Comment by Swati4star** [comment]
Sure, I'll fix the remaining issues @sasfmlzr 

Great work! You did a great work here!

**Comment by sasfmlzr** [comment]
Fixed.
image

image

image

**Comment by sasfmlzr** [comment]
The bottom sheet is not that much visible in black theme
What color do you want?

**Comment by Swati4star** [comment]
@sasfmlzr white background on bottom strip & `View Files` in black color. I hope, this looks good.

**Pull request merged**
