### PR TITLE
added more validation to user input

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description

added more validation to user input in split fragment. now it's working for all kinds of input

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ni3verma** [comment]
code climate says **avoid too many return statements**
there are so many cases.. what should I do? :confused:

**Comment by Swati4star** [comment]
You can leave code climate tests

**Comment by Swati4star** [comment]
@sidhuparas @srv-twry review this. check for all the possible inputs

**Comment by srv-twry** [comment]
> code climate says avoid too many return statements
there are so many cases.. what should I do? confused

@Ni3verma 
Do one thing. Define an integer variable called `validityStatus` initializing it to zero. In every case where you're returning an integer, instead of returning that value, assign it to the `validityStatus` variable and then return it in the end of the method. That'll make code climate happy :wink:

**Comment by Swati4star** [comment]
Great @Ni3verma 

I think you can have good test cases for your previous PR now 👍

**Pull request merged**
