### PR TITLE
Feat : Add logo in navigation drawer

### LINKED ISSUE #107: Add logo in the navigation Drawer
Adding logo in the navigation drawer will improve the UI of the app. Many apps use this approach.  
Example:

### PR DESCRIPTION
**Pull request by Pritom14**
Fix #107

### CODE REVIEW

**Comment by Swati4star** [comment]
@Pritom14 
The changes look great. 
Squash these changes into a single commit. (You can check how to stash here : https://github.com/Swati4star/Images-to-PDF/blob/master/CONTRIBUTING.md#8-stash-the-changes-after-review-is-done )

**Comment by Pritom14** [comment]
@Swati4star could you please review the PR

**Comment by Pritom14** [comment]
Could you please check if the commits are squashed?
I am having some difficulty in checking whether they are squashed

**Comment by Swati4star** [comment]
Check the number of commits on this PR. They are still 2.
After squashing, it should be 1.
screen shot 2018-06-23 at 7 13 42 pm

**Comment by Swati4star** [comment]
You might get problem in squashing because 'merge' commit is one of your commit. 
You can close this PR, fork the repo & create a new one.

**Pull request closed without merging**
