### PR TITLE
Maintain Aspect Ratio of images

### LINKED ISSUE #93: Aspect ratio of images is not maintained
Add an option to do so.

- Maintain Aspect ratio, or,
- Fit to the page

### PR DESCRIPTION
**Pull request by mobiuscog**
# Description
When adding an image, it will resize, keeping the aspect ratio.
I created a new method to calculate the correct image size, and called it from the correct place.

Fixes #93

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

NB The checkstyle reports two errors, but these are in the auto-generated code, and as such I ignored them.
The new method has also been tested locally using unit tests - I would have added them but there is currently no structure for this.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@mobiuscog The changes look good. I'll just verify it once locally 👍

**Comment by Swati4star** [comment]
@mobiuscog I am facing this problem:
screen shot 2018-07-08 at 8 54 01 pm

The actual image is occupying very less space. You should zoom it out.

**Comment by mobiuscog** [comment]
Is that image very small to begin with ? It shouldn't be reduced in size if it's smaller than the document size, and if it just scales up to fit, small images could become very pixelated if they are being scaled beyond their original size.

**Comment by Swati4star** [comment]
We just don't want this much white space around the image.
The image doesn't get that much pixelated. I would suggest you scale the image.

**Comment by mobiuscog** [comment]
I've updated with all of the changes you requested.

**Comment by Swati4star** [comment]
looks perfect. I'll merge it.

**Pull request merged**
