### PR TITLE
Fix for #216

### LINKED ISSUE #216: Show previous image button also in filter image screen
The filter image screen currently has this UI:
screen shot 2018-07-14 at 4 51 05 pm

- Add a previous arrow button also by the left of `Showing 1 of 1 images`
- It should allow users to edit previous image

### PR DESCRIPTION
**Pull request by vyankatesh24**
# Description

added back button in Filter image activity
image

Fixes #216 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

### CODE REVIEW

**Comment by Swati4star** [comment]
Have you tested the functionality? Is it working fine?

**Comment by vyankatesh24** [comment]
Yes

**Comment by vyankatesh24** [comment]
Images are changing as per button 
backward and forward

**Comment by vyankatesh24** [comment]
You may test again...

**Comment by Swati4star** [comment]
I'll merge it soon!

**Pull request merged**
