### PR TITLE
Decreased text size in merge view

### LINKED ISSUE #285: [Merge PDF] Full file path is not coming up on the buttons
Observe this gif:
my

### Expected behaviour
The full path (along with filename) should be there on the buttons

### PR DESCRIPTION
**Pull request by eddygta17**
# Description

Dcreased text size in merge view

Fixes #285 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
The issue is still there. I checked it locally. 
screen shot 2018-07-28 at 8 44 13 am
Only the text size is changed, the full file path is not yet coming up.

**Comment by eddygta17** [comment]
It's coming up on my device,  i cannot fix this.

**Comment by Swati4star** [comment]
Pick up some other issue then. This isn't solving the problem.

**Comment by Swati4star** [comment]
Closing this PR, since it doesn't solve the issue.

**Pull request closed without merging**
