### PR TITLE
#320 Lock image for encrypted pdfs

### LINKED ISSUE #320: Show a lock icon by the side of encrypted PDFs in View Files
### Steps
Go to `View Files` from the navigation drawer

### Expected behaviour
Show a lock icon at the top right corner of the crad of the PDFs (which are encrypted)

This is just to show a difference between encrypted & unencrypted PDFs

### PR DESCRIPTION
**Pull request by vishalkalra9**
# Description

Did some UI changes to show a lock icon in case of encrypted PDFs in list.

Fixes #320 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@vishalkalra9 Can you post a screenshot of the new UI also?

**Comment by Swati4star** [comment]
@vishalkalra9 Also, there a few checkstyle errors. Look into the travis link!

This is your first contribution to the project! If you face any problem with the travis or something else, you can comment on this thread!

**Comment by vishalkalra9** [comment]
Sure. Please find below the screenshot of the same.

lock_image

**Comment by Swati4star** [comment]
@vishalkalra9 The UI looks good. 👍

**Comment by vishalkalra9** [comment]
@Swati4star  I've fixed the checkstyle error.

**Comment by Swati4star** [comment]
@vishalkalra9 Great! Congrats on your first commit to the application! :D

**Comment by vishalkalra9** [comment]
@Swati4star Thanks :D

**Pull request merged**
