### PR TITLE
581-ThemeApply-on-HelpActivity

### LINKED ISSUE #581: Theme is not getting applied on Help Activity
### Description
    Theme is not getting applied on Help Activity
### Steps to reproduce
   * Goto Settings
   * Change Theme
   * Now open Help Activity from Navigation Drawer
### Actual behaviour
image
image

### Expected behaviour
    Theme should be applied.

### PR DESCRIPTION
**Pull request by AfolabiDonko**
# Apply theme on Help Activity

Apply the theme change on Help Activity
Fixes #581 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
53794366_726566451070825_5342108575059673088_n
54255710_317734105598519_1909746848705282048_n

### CODE REVIEW

**Comment by Swati4star** [comment]
Not a new issue. You can do the changes in this PR only

**Comment by sidhuparas** [comment]
@AfolabiDonko Please make the required change then.

**Comment by AfolabiDonko** [comment]
ok, I will do it now

**Comment by AfolabiDonko** [comment]
53783942_229798937856834_8793920314217070592_n


The new change !

**Comment by Swati4star** [comment]
Great 👍

**Pull request merged**
