### PR TITLE
create unit test for ImageUtil.class

### PR DESCRIPTION
**Pull request by snufflesrea**
# Description
Add unit test for ImageUtil.class
Mockito dependency added to graddle file

Fixes #(issue)
#132 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@snufflesrea there are merge conflicts. Resolve them.

**Comment by Swati4star** [comment]
@snufflesrea Also, can you tell, how should i run these tests?

**Comment by Swati4star** [comment]
@snufflesrea Any updates?

**Comment by Swati4star** [comment]
Closing because of no response!
If you start working on it, feel free to open this PR.

**Comment by snufflesrea** [comment]
Sorry.  Have been one week without internet connection. I will relook again later when free

**Pull request closed without merging**
