### PR TITLE
View Files

### PR DESCRIPTION
**Pull request by Sandip75**
Here I disable delete and sort icon when I have no pdf.

### CODE REVIEW

**Comment by Swati4star** [comment]
There are merge conflicts.

**Comment by Swati4star** [comment]
@Sandip75 Are you working on this one?

**Comment by Sandip75** [comment]
Yes I am working but busy in learning few things

**Comment by Swati4star** [comment]
This is a very small change. This shouldn't take up that much amount of time.

**Comment by Swati4star** [comment]
@Sandip75 The changes look good. Resolve the merge conflicts & squash the commits into one.

**Comment by Swati4star** [comment]
Closing because of no response!

**Comment by Sandip75** [comment]
It's complete ?

**Comment by Swati4star** [comment]
How is it complete? You haven't resolved the merge conflicts yet.

**Comment by Sandip75** [comment]
Okay

**Comment by Sandip75** [comment]
Actually I need to learn git 
No problem

**Pull request closed without merging**
