### PR TITLE
Split PDF bug fixed

### LINKED ISSUE #750: [Split PDF] PDF gets created even when there is one page in PDF
In `Split PDF` PDF is getting created even when there is one page in PDF.

### Steps to reproduce
* Open `Split PDF`
* Select PDF (Which has only one page)
* Click `Split PDF` button.

### Actual behaviour
* New PDF gets created with by suffixing `_1` to its name and only the snackbar is shown `PDF has only one page can't be split...` 

* The snackbar is shown even when there are multiple pages in PDF and we create only one split of it.

### Expected behaviour
New PDF shouldn't be created.

### PR DESCRIPTION
**Pull request by rob729**
# Description
<a href="https://imgflip.com/gif/30gjkw"></a>

Fixes #750 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@vyankatesh24 Please review this PR.

**Comment by vyankatesh24** [comment]
@rob729  There is a bug
* Select PDF (more than 1 page)
* Enter split as `1-2`
* Click `Split PDF`
* snack bar is shown `Selected PDF has 1 page .....`  also file is not created.

**Comment by rob729** [comment]
@vyankatesh24 so what should be the expected behavior?
Should I create the PDF or change the snack bar message when full range of a PDF is entered in a single range?

**Comment by vyankatesh24** [comment]
* If full range split is given change snackbar message. 
* If other split is given (1-2 when there are 5 pages )  PDF should be created with `PDF Created ` snackbar.

**Comment by rob729** [comment]
@vyankatesh24 I have done the requested changes.
Please review the changes.

**Comment by vyankatesh24** [comment]
@rob729 
Still, it is not working for the following case
* Select PDF (more than 1 page)
* Enter split as `1`
* Click `Split PDF`
* snack bar is shown `Selected PDF has 1 page .....`  also file is not created.

**Comment by rob729** [comment]
@vyankatesh24 I have fixed the bugs.
Please review the PR again.

**Comment by vyankatesh24** [comment]
@rob729 
Now working fine for all cases.
Just a small change 
I think when there should same snackbar message for the following cases.
* PDF has 1 page and split entered is `1`
* PDF has 5 pages and split entered is `1-5`
as the meaning of is the same, we will be creating the same PDF again.

What do you think?

**Comment by vyankatesh24** [comment]
The message can be `Entered split range will create Selected PDF again!`

**Comment by rob729** [comment]
@vyankatesh24 I think the second one is better.

**Comment by vyankatesh24** [comment]
> The message can be `Entered split range will create Selected PDF again!`

This?

**Comment by rob729** [comment]
> > The message can be `Entered split range will create Selected PDF again!`
> 
> This?

Yes

**Comment by rob729** [comment]
> Update the `PDF contains only one page... ` and remove this.
> Because that string is of no use now. Right?

That string can be used to tell the user that there is no use of using such PDF(of one page) in the split PDF.

**Pull request merged**
