### PR TITLE
Issue 562, Navigation drawer

### LINKED ISSUE #562: Add sections and section headers in navigation drawer
### Steps
Open navigation drawer
screenshot 2019-02-17 at 3 03 15 pm

### Actual behaviour
All the items are listed in one big group

### Expected
- Add the items in different sections (in accordance with the home page)

### PR DESCRIPTION
**Pull request by AfolabiDonko**
# Description

Add sections and section headers in navigation drawer
52832699_2266760323644926_9149592551773175808_n

Fixes #562 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by srv-twry** [comment]
@AfolabiDonko Kindly use the template. There are supposed to be used.

**Comment by AfolabiDonko** [comment]
@srv-twry ok ! I will do it now

**Comment by AfolabiDonko** [comment]
52832699_2266760323644926_9149592551773175808_n

**Comment by AfolabiDonko** [comment]
@srv-twry 
the Navigation drawer has been divided into several sections according tothe home page

**Comment by Swati4star** [comment]
Hi @AfolabiDonko Are you a gssoc participant?

**Pull request merged**
