### PR TITLE
Update strings.xml in spanish

### LINKED ISSUE #538: Update to Spanish (ES) translation to strings.xml
My followup to https://github.com/Swati4star/Images-to-PDF/issues/526 with some corrections + translated a new section that was added after the initial translation.

I don't know how to pull-request, if it can be created on my behalf like last time, I would appreciate.

Here is the forked branch: https://github.com/ajax333221/Images-to-PDF/blob/master/app/src/main/res/values-es/strings.xml

### PR DESCRIPTION
**Pull request by Swati4star**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

Fixes #538

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@ajax333221 Is it done? or anything left?

**Comment by ajax333221** [comment]
@Swati4star it is done now, triple-rechecked it :)

**Comment by ajax333221** [comment]
I panicked and unforked and reforked to eliminate some branching complicated things I was experiencing:

https://github.com/ajax333221/Images-to-PDF/tree/master/app/src/main/res/values-es

**Comment by Swati4star** [comment]
I am opening a new PR.

**Pull request closed without merging**
