### PR TITLE
Update to api 29

### PR DESCRIPTION
**Pull request by Rautarchit001**
updated library of image picker

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@Rautarchit001 - Fix the travis checks also. We cant merge this PR with checks failing.

**Comment by codegsaini** [comment]
> updated library of image picker
> 
> # Description
> 
> Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
> If there are any UI change, please include the screenshots also.
> 
> Fixes #(issue)
> 
> ## Type of change
> Just put an x in the [] which are valid.
> - [ ] Bug fix (non-breaking change which fixes an issue)
> - [ ] New feature (non-breaking change which adds functionality)
> 
> # How Has This Been Tested?
> 
> Please describe the tests that you ran to verify your changes.
> - [ ] `./gradlew assembleDebug assembleRelease`
> - [ ] `./gradlew checkstyle`
> 
> # Checklist:
> - [ ] My code follows the style guidelines of this project
> - [ ] I have performed a self-review of my own code
> - [ ] I have commented my code, particularly in hard-to-understand areas
> - [ ] I have made corresponding changes to the documentation
> - [ ] My changes generate no new warnings
> 

Sir, looks like provided description of pull request is auto generated for the purpose to make you understand how to write a good description. You should edit it accordingly to better elaborate your changes.

**Comment by codegsaini** [comment]
In commit 4ecb9e027aa26ad2a9e38a201206b15c7d3eb91c you are updating `compileSdkVersion` and `targetSdkVersion` to `29` and `minSdkVersion` to 16 as well, which may produce error.

**Reason?**
Version 28 (intended for Android Pie and below) is the last version of the legacy support library. So, all support library will stop working if you change `compileSdkVersion` to higher than `28`.

**Solution?**
The only solution is to migrate from Support library to androidx. In android studio you can simply migrate to androidx but it can also produce some error which should be fixed by changing code as required to support androidx and then we can compile app on version higher than 28 (in this case 29).

**SideNote~**
I am working on it from now... you can wait until I push related commit or you can try yourself.

Happy coding!

**Comment by Rautarchit001** [comment]
Thank you hope you will succeed in that i have solved some errors after updating to androidx but there is only one error left is image is not showing in preview section and pdf does not export.

Image picking error is solved by updating library but after that this one error is left only.

**Pull request closed without merging**
