### PR TITLE
Merge file selection bug fixed

### LINKED ISSUE #759: Bug in Merge PDF in file selection
### Steps to reproduce
* Open `Merge PDF`
* Select files using BottomSheet
* Remove Files using `X` icon
* Open Bottom Sheet
* The files which were selected, remain checked 
* Now Uncheck them, They get added in `selected files`

### Expected behaviour
The files which were removed using `X` icon, should be unchecked.

### Actual behaviour
The files which were removed using `X` icon, remain checked.

### PR DESCRIPTION
**Pull request by rob729**
# Description

<a href="https://imgflip.com/gif/31jilw"></a>

Fixes #759

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@vyankatesh24  Please review the PR.

**Comment by rob729** [comment]
@vyankatesh24 Are you always getting this error when you are trying to select the file(s)?

**Comment by rob729** [comment]
@vyankatesh24 how should I solve this issue as I am not able to produce it on my device?

**Comment by vyankatesh24** [comment]
I'll check again and let you know. 
Otherwise will ask some other mentor to test and review the PR

**Comment by rob729** [comment]
Ok

**Comment by vyankatesh24** [comment]
I've tried again; not able to select files!
@sidhuparas  can you please have look at this PR?

**Comment by vyankatesh24** [comment]
@rob729 Builds are failing, please have a look!

**Comment by rob729** [comment]
@vyankatesh24 That issue is fixed.
Has anybody else reviewed the PR?

**Comment by rob729** [comment]
@Swati4star Please review this PR.

**Comment by sidhuparas** [comment]
@rob729 I have tested it as well and I am getting the same error as @vyankatesh24. The app is getting crashed as soon as I tries to add a file.

**Comment by rob729** [comment]
@vyankatesh24 @sidhuparas Do you have any suggestion on how should I solve this issue because I am not able to reproduce the error which can be seen in the gif attached above?

**Comment by sidhuparas** [comment]
@rob729 I’m really sorry as I am outstation now but the error is same as that of Vyankatesh. Compare your modified code with the original one. This should show you the path to resolve the issue.

**Pull request closed without merging**
