### PR TITLE
FAQS

### PR DESCRIPTION
**Pull request by ak2502**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
are you going to add something here? Is it a work in progress?

We are maintaining FAQs in strings.xml now

**Comment by ak2502** [comment]
I thought we have to add only questions.
What else should I add?

**Comment by Swati4star** [comment]
No no. this wasnt for just adding questions.
These FAQs are for users to be displayed in app.
See sample PR https://github.com/Swati4star/Images-to-PDF/pull/845 if you are interested in adding FAQs

we are not maintaining FAQ.md anymore.

**Comment by Swati4star** [comment]
More FAQs have already been added.

**Comment by Swati4star** [comment]
If you still feel some information is missing, you may create a new PR

**Pull request closed without merging**
