### PR TITLE
Configure test coverage 

### LINKED ISSUE #947: Configure test coverage on code climate
Currently, code climate does not calculate test coverage.

https://codeclimate.com/github/Swati4star/Images-to-PDF/code?sort=maintainability

Ref: https://docs.codeclimate.com/docs/configuring-test-coverage

### PR DESCRIPTION
**Pull request by sreekesh93**
# Description

This PR supports by configuring the test coverage using jacoco.

Fixes #947

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] `./gradlew jacocoTestReport`

### CODE REVIEW

**Comment by Swati4star** [comment]
Can you share more details around this library?
How would I be able to see the coverage details?

**Comment by sreekesh93** [comment]
JaCoCo is a free code coverage library for Java, which has been created by the EclEmma team. This plugin analyse the test coverage and branch coverage.

To get report run ./gradlew jacocoTestReport

The report will be created under app/build/reports/jacoco/jacocoTestReport/html/index.html file

**Comment by Swati4star** [comment]
Thanks for this implementation. But, I was hoping to integrate the coverage with some online tools. Like, travis or Code climate. (as mentioned in the issue)

I won't be able to run coverage locally everytime.  It'll be useful only if some service could tell the current coverage on PRs and codebase.

**Comment by sreekesh93** [comment]
We can make build fail if test coverages are less with this jacoco setup.
Will that be use ful?

**Comment by Swati4star** [comment]
codecov seems good. Can you configure it with our project?

**Comment by sreekesh93** [comment]
Sure

**Comment by Swati4star** [comment]
Is it ready for review?

**Comment by sreekesh93** [comment]
Hi Swati,
Ya I configuraed all necessary steps it's uploading to coverage website but
nt able to see any reports.

**Pull request closed without merging**
