### PR TITLE
#75 - Sort Images by Size

### PR DESCRIPTION
**Pull request by anandkumarkparmar**

### CODE REVIEW

**Comment by Swati4star** [comment]
device-2018-06-05-212139
The UI looks a bit weird. Can we somehow increase the size of the arrow?

**Comment by anandkumarkparmar** [comment]
@Swati4star, What about this one? 

whatsapp image 2018-06-05 at 21 40 44

**Comment by Swati4star** [comment]
This one looks better. But still, let's search for something like previous one only.
If not, then we can have the second one.

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, I have tried difference options, but I didn't like any of them. I guess we can proceed with above one. Take the call please.

**Comment by Swati4star** [comment]
@anandkumarkparmar Let's go ahead with the second screenshot.
Push the commit for that. Squash them & I'll merge it.

**Comment by anandkumarkparmar** [comment]
Review please... @Swati4star

**Comment by Swati4star** [comment]
Merged! Thanks a lot @anandkumarkparmar ! 👍

**Pull request merged**
