### PR TITLE
Lottie animation 187

### PR DESCRIPTION
**Pull request by vyankatesh24**
# Description

Added LottieAnimationLayout

image

Fixes #(issue)
#187 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

### CODE REVIEW

**Comment by Swati4star** [comment]
Can you create a new dialog/fragment & add animation over that? It doesn't look that good on this screen.

**Comment by vyankatesh24** [comment]
Ok

**Comment by vyankatesh24** [comment]
What about this?

image

**Comment by Swati4star** [comment]
Make it background color white. And at the bottom, write text "Converting your files to PDF".

Also, can you change the yellow color in the animation file to that of our app's orange color.

**Comment by vyankatesh24** [comment]
image


@Swati4star  
Have a look and comment !

**Comment by Swati4star** [comment]
@vyankatesh24 This looks great! Just one enhancement. Add a text at the bottom of this dialog "Converting your files to PDF. Please wait..." (in orange color only)

**Comment by vyankatesh24** [comment]
image

**Comment by vyankatesh24** [comment]
Sorry!
I will update the message.

**Comment by vyankatesh24** [comment]
image

**Pull request merged**
