### PR TITLE
watermark working properly

### LINKED ISSUE #672: Add Watermark not working
`Add Watermark` is not working when used explicitly from an option on `Home Fragment` but works when applied while creating PDF in `ImagesToPDF Fragment`. 

### Steps to reproduce 
* Add Watermark
* Select File 
* Choose add watermark option
* Enter text and click Ok

### Expected behaviour
The watermark should be applied

### Actual behaviour
The watermark doesn't get applied

### PR DESCRIPTION
**Pull request by rob729**
# Description

Fixes #672 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@Swati4star @vyankatesh24 Please review this PR.
I am a GSSoC Participant.
Slack username: Robin(P)

**Comment by vyankatesh24** [comment]
@rob729 
Well Done :+1: 
The solution is working properly

**Comment by vyankatesh24** [comment]
Congrats on your first contribution to this project :+1:

**Comment by vyankatesh24** [comment]
@Swati4star Why the Travis build didn't start.

**Pull request merged**
