### PR TITLE
Bug fixed of home scrolling down

### LINKED ISSUE #412: [Home page] fragment automatically scrolls down
- Go to some other fragment
- then, come to `create PDF` fragment.

### Actual behaviour
The fragment scrolls down

### Expected behaviour
It shouldn't

### PR DESCRIPTION
**Pull request by anirudh8860**
Fixes #412, need to add android:focusableInTouchMode="true" to parent layout, not child.

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by anirudh8860** [comment]
Hey @Swati4star just check if scrolling issue is still there

**Comment by Swati4star** [comment]
@anirudh8860 Did you check if this fixes the issue?

**Comment by anirudh8860** [comment]
Yes I did. It worked on 1 emulator and my device.

**Comment by Swati4star** [comment]
Awesome!

**Pull request merged**
