### PR TITLE
fix-#588 add filter in history

### LINKED ISSUE #588: Add `Filter` option in history section
Add `Filter` option in history section

### Steps to reproduce
Go to history from navigation drawer or home page

### Expected behaviour
- add a `filter` menu option in the title bar 
- on selecting it, open up a dialog with checkboxes on following options:
Created, Deleted, Renamed, Rotated, Printed, Decrypted, Encrypted, Inverted
- By default, all the option should be checked
- Based on the options selected by the user, show corresponding items only.

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description

Fixes #588 
showing history based on selected filter

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ni3verma** [comment]
screenshot_20190306-125558
screenshot_20190306-125545
screenshot_20190306-125540

**Comment by Swati4star** [comment]
@vyankatesh24 review this PR

**Comment by vyankatesh24** [comment]
> @vyankatesh24 review this PR

Ok :+1:

**Comment by Ni3verma** [comment]
@vyankatesh24 
I already asked about it specifically. 
see here https://github.com/Swati4star/Images-to-PDF/issues/588#issuecomment-469711289
Swati told me to not persist anything and just **select all** by default everytime.

**Comment by vyankatesh24** [comment]
> @vyankatesh24
> I already asked about it specifically.
> see here [#588 (comment)](https://github.com/Swati4star/Images-to-PDF/issues/588#issuecomment-469711289)
> Swati told me to not persist anything and just **select all** by default everytime.

Yeah do not persist permanently in Shared Prefs
Just till activity is open, as it will be good UX.
When I close and open the History activity again All should be selected.

**Comment by Ni3verma** [comment]
@vyankatesh24 okk

**Comment by Ni3verma** [comment]
@vyankatesh24 Please review, I have made the requested changes

**Comment by vyankatesh24** [comment]
> @vyankatesh24 Please review, I have made the requested changes

Well done! I've tested.
But there is a bug when we click on `SELECT ALL` and again open Filter Dialog, only the boxes which are checked earlier remains checked and others unchecked, All checkboxes should be checked in this case.

Just make these changes else everything is good :+1:

**Comment by Ni3verma** [comment]
@vyankatesh24 Done

**Pull request merged**
