### PR TITLE
added fdroid-badge

### PR DESCRIPTION
**Pull request by DJCrashdummy**
as f-droid builds should be up to date in future, you are hopefully ok with an fdroid-badge?

### CODE REVIEW

**Comment by DJCrashdummy** [comment]
btw: is the [description at fdroid](https://f-droid.org/packages/swati4star.createpdf/) still ok, or does it also need an update?

**Comment by Swati4star** [comment]
It would be nice, if we can have this description (this is on google play also)

```
PDF CONVERTER is an easy to use application to convert Images to PDF. This is basically an images to PDF Converter. The simplicity of this app makes it an ultimate PDF Converter for your device.

<b> Some major features of PDF Converter app </b>  :
✔️ No internet connection required ( ⭐)
✔️ No in-app purchases. EVERYTHING FREE!!  ( ⭐)
✔️ Smooth and easy to use interface
✔️Takes up only a few seconds
✔️ No limit on the number of PDFs conversion
✔️ Select images from camera/gallery
✔️ Image enhancement features
✔️ Crop images before creating a PDF
✔️ View PDF files
✔️ Delete PDF files
✔️ Extract images from PDF
✔️ Split PDF
✔️ Merge PDF
✔️ Convert text files to PDF
✔️ Manage your PDF files
✔️ Remove pages from PDF
✔️ Reorder PDF pages
✔️ Share the created PDFs with your friends
✔️ Easily manage the PDFs created by our app

Supported input types:
✔️JPG
✔️PNG
...and other image formats!

This application can be called as a PDF Converter, Images to PDF Converter, JPG to PDF Converter, BMP to PDF Converter, PNG to PDF Converter, GIF to PDF Converter, Image to pdf converter, Convert JPG to PDF, Convert to Pdf, PDF Converter, Convert JPG to PDF, JPG to PDF Document Converter.

We are constantly working on improving the PDF Conversion performance. If you have any suggestions or complaints, feel free to mail to us at swati4star@gmail.com !!
```

**Comment by DJCrashdummy** [comment]
finally i managed to make the merge request to f-droid working with your desired description (just corrected some missing & superfluous spaces)...

but the maintainers want a more clear description and remove or at least rework the SEO-attempt (the second last paragraph):
> [...] Does it only convert images to PDF, or also other document types? Depending on that, I fully agree with you shrinking this to something like "This app can be called (Images to) PDF Converter or PDF Creator. It can convert BMP, GIF, JPG and PNG files." (add the other types if there are any). [...]

_this is the essential part quoted from https://gitlab.com/fdroid/fdroiddata/merge_requests/3761#note_110724585_

if you are not on gitlab, let me or @IzzySoft know what you think about it. Thanks!

**Comment by Swati4star** [comment]
@DJCrashdummy The app can do a different type of conversions too, like,
images to pdf
text to pdf 
pdf to images
bar codes to pdf
qr codes to pdf
pdf to text (in progress)
various operations on PDF (split, merge, encrypt, decrypt, compress, reorder)


You can modify the description accordingly.

**Pull request merged**
