### PR TITLE
Remove stale 'view pdf' button from InvertPdfFragment

### LINKED ISSUE #671: Bug in Invert PDF
The button `View  PDF` remains visible even after selecting the next PDF.

### Steps to reproduce
* Invert PDF
* select pdf
* click `Invert PDF`
* After Inverting `View  PDF` button becomes visible
* Now select another PDF.

### Expected behaviour
The button `View  PDF` should become invisible after selecting the next PDF.

### Actual behaviour
The button `View  PDF` remains visible even after selecting the next PDF.

### PR DESCRIPTION
**Pull request by qualitymanifest**
Fixes #671

As a note - I am new to this project, but from a quick look around, it looks like this issue exists in other features as well. The only other ones I have taken a look at are Remove Pages and Reorder Pages and they both exhibit the same behavior. The fix would probably be similar for other features.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by vyankatesh24** [comment]
Congratulations! on your first contribution to this project.
We will look at issues you have noted.

**Comment by vyankatesh24** [comment]
Also, from next time comment on issue when you start working so no other person will work on it :+1:

**Comment by vyankatesh24** [comment]
@qualitymanifest 
Are you GSSoC participant?

**Comment by qualitymanifest** [comment]
> Are you GSSoC participant?

I am not, I just found this issue by searching for Java issues labeled "good first issue". I'm mainly experienced with JS and trying to gain some experience with Java.
> from next time comment on issue when you start working so no other person will work on it

Will do!

**Pull request merged**
