### PR TITLE
#84 - Change in the existing UI

### PR DESCRIPTION
**Pull request by anandkumarkparmar**

### CODE REVIEW

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, 

Can you please check, why it is failing?

**Comment by Swati4star** [comment]
I am looking into it.

**Comment by Swati4star** [comment]
Hi. Check the new branch I created : https://github.com/Swati4star/Images-to-PDF/tree/ui

This commit 15150d843b5f69d4444fabba2c6b2d8a463584fb is fixing the issue

**Comment by anandkumarkparmar** [comment]
Hi @Swati4star, Please review this PR. I have merged your commit from 'ui' branch.

PS: Please let me know, if you want all these in one commit.

**Comment by Swati4star** [comment]
I reviewed your code. It looks good.

Yes please, squash it into a single commit.

**Comment by anandkumarkparmar** [comment]
Done. @Swati4star

**Comment by Swati4star** [comment]
Great! I'll submit it by tomorrow :+1:

**Comment by Swati4star** [comment]
Thanks @anandkumarkparmar 👍

**Comment by anandkumarkparmar** [comment]
Welcome. @Swati4star

**Pull request merged**
